PHRI/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic.base import RedirectView


from users.views import landing, terms, about

urlpatterns = i18n_patterns(
    url(r'^$', landing, name='landing'),
    url(r'^', include('data_entry.urls', namespace='data_entry')),
    url(r'^database/', include('database.urls', namespace='database')),
    url(r'^survey/', include('surveys.urls', namespace='surveys')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^users/password/', include('password_reset.urls')),
    url(r'^favicon.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^terms', terms, name='terms'),
    url(r'^about', about, name='about')
)


### FOR TESTING ONLY ###
from django.http import Http404
from django.core.exceptions import PermissionDenied

def error_403(request):
    raise PermissionDenied

def error_404(request):
    raise Http404

def error_500(request):
    raise Exception('Error!!')

urlpatterns += [
    url(r'^403$', error_403),
    url(r'^404$', error_404),
    url(r'^500$', error_500),
]

data_entry/urls.py
from django.conf.urls import url, include

from . import views


patients = [
   url(r'^$', views.patient_index, name='index'),
   url(r'^test$', views.patient_index_test, name='index_test'),
   url(r'^(?P<patient_id>\d+)/$', views.patient_details, name='details'),
   url(r'^(?P<patient_key>.+)/reports/medical/$', views.medical_report, name='medical_report'),
   url(r'^(?P<patient_key>.+)/reports/medical/email$', views.email_medical_report, name='email_medical_report'),
   url(r'^(?P<patient_key>.+)/reports/patient/$', views.patient_report, name='patient_report'),
   url(r'^(?P<patient_key>.+)/reports/patient/email$', views.email_patient_report, name='email_patient_report'),
]
# reverse('data_entry:patients:index')
# reverse('data_entry:patients:detail')


urlpatterns = [
    url(r'^form$', views.form, name='form'),
    url(r'^form/test$', views.form_test, name='form_test'),
    url(r'^guidelines$', views.guidelines, name='guidelines'),
    url(r'^recommendations$', views.recommendations, name='recommendations'),
    url(r'^patients/', include(patients, namespace='patients')),
]

surveys/urls.py
from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^$', views.display_survey, name='dynamic_survey'),
    url(r'^save/$', views.ajax_save_survey, name='save_survey'),
    url(r'^iapply/$', views.apply_survey, name='iapply'),
    url(r'^extiapply/$', views.apply_external_survey, name='extiapply'),
    url(r'^external_survey/agreed$', views.agreed_external_survey, name='extsurveyagreed'),
]

surveys/models.py
from django.db import models
from utils.models import CreateModifactionDateMixin
from utils.models import CreatedModificationUserMixin
from utils.models import PublishDataMixin
import shortuuid


class Survey(CreateModifactionDateMixin, CreatedModificationUserMixin, PublishDataMixin):
    key = models.CharField(max_length=22, null=False, unique=True)
    title = models.CharField(max_length=128, null=False)
    description = models.TextField(null=True)
    def __init__(self, *args, **kwargs):
        super(Survey, self).__init__(*args, **kwargs)
        if not self.key:
            self.key = shortuuid.uuid()
        if kwargs.get('title'):
            self.title = kwargs['title']

    def __str__(self):
        return 'id=%s, title = %s, created = %s, is_published=%s' % (
            self.id,
            self.title,
            self.created.strftime('%H:%M, %d %B, %Y'),
            self.publish)

    def get_absolute_url(self):
        return "/view_survey/%s" % self.key

    def get_report_data(self):
        headers = ["user", "created"]
        rows = []
        
        # creating headers
        for q in self.questions.all():
            if q.type == 'checkbox':
                for ch in q.checkboxquestion.choices.all():
                    headers.append(q.title + ' [' + ch.label + ']')
            else:
                headers.append(q.title)

        # Generating rows
        for r in self.responses.all():
            a_row = [r.user.user_name, r.created]
            for a in r.answers.all():
                if a.question.type == 'multiplechoice':
                    a_row.append(a.answermultiplechoice.body)
                if a.question.type == 'checkbox':


                    options_selected = a.answercheckbox.body.split('#@#')
                    all_checkbox_choices = a.question.checkboxquestion.choices.all()
                    all_checkbox_choices_label = [x.label for x in all_checkbox_choices]

                    for chch in all_checkbox_choices:
                        if chch.free_text:
                            inserted = False
                            for os_str in options_selected:
                                if os_str not in all_checkbox_choices_label:
                                    a_row.append(os_str)
                                    inserted = True
                                    break
                            if not inserted:
                                a_row.append(False)
                        else:
                            a_row.append(chch.label in options_selected)



                if a.question.type == 'paragraph':
                    a_row.append(a.answerparagraph.body)
                if a.question.type == 'numeric':
                    a_row.append(a.answernumeric.body)
                if a.question.type == 'text':
                    a_row.append(a.answertext.body)
            rows.append(a_row)

        return dict(headers=headers, rows=rows)

    class Meta:
        ordering = ['id']


class Question(CreateModifactionDateMixin, CreatedModificationUserMixin, PublishDataMixin):
    survey = models.ForeignKey(Survey, related_name='questions')
    QUESTION_TYPE_CHOICES = (
        ('multiplechoice', 'MultipleChoiceQuestion'),
        ('checkbox', 'CheckboxQuestion'),
        ('paragraph', 'ParagraphQuestion'),
        ('numeric', 'NumericQuestion'),
        ('text', 'TextQuestion')
    )
    type = models.CharField(choices=QUESTION_TYPE_CHOICES, max_length=25)
    title = models.CharField(max_length=500, null=False)
    important_text = models.CharField(max_length=500, blank=True, null=True)
    help_text = models.CharField(max_length=500, blank=True)
    is_required = models.BooleanField(default=True)

    def __str__(self):
        return 'No.%d, title=%s, type=%s, required=%s' % (self.order, self.title, self.type, self.is_required)

    class Meta:
        ordering = ["order"]


class ParagraphQuestion(Question):
    max_no_characters = models.IntegerField()

    def __init__(self, *args, **kwargs):
        super(Question, self).__init__(*args, **kwargs)
        self.type = "paragraph"


class NumericQuestion(Question):
    min_value = models.FloatField(null=True)
    max_value = models.FloatField(null=True)

    def __init__(self, *args, **kwargs):
        super(Question, self).__init__(*args, **kwargs)
        self.type = "numeric"

    def __str__(self):
        return 'title=%s, min=%f, max=%f' % (self.title, self.min_value, self.max_value)


class CheckboxQuestion(Question):
    min_checked = models.IntegerField(null=True)
    max_checked = models.IntegerField(null=True)

    def __init__(self, *args, **kwargs):
        super(Question, self).__init__(*args, **kwargs)
        self.type = "checkbox"


class CheckboxChoice(models.Model):
    question = models.ForeignKey(CheckboxQuestion, related_name='choices')
    label = models.CharField(max_length=200)
    order = models.IntegerField()
    free_text = models.BooleanField(default=False)

    def __str__(self):
        return 'label%d: %s' % (self.id, self.label)

    class Meta:
        ordering = ["order"]


class MultipleChoiceQuestion(Question):
    def __init__(self, *args, **kwargs):
        super(Question, self).__init__(*args, **kwargs)
        self.type = "multiplechoice"


class MultipleChoice(models.Model):
    question = models.ForeignKey(MultipleChoiceQuestion, related_name='choices')
    label = models.CharField(max_length=200)
    order = models.IntegerField()
    free_text = models.BooleanField(default=False)

    def __str__(self):
        return 'label%d: %s' % (self.order, self.label)

    class Meta:
        ordering = ["order"]


class TextQuestion(Question):
    max_no_characters = models.IntegerField(null=True)

    def __init__(self, *args, **kwargs):
        super(Question, self).__init__(*args, **kwargs)
        self.type = "text"

    def __str__(self):
        return 'title=%s, max_no_characters=%d' % (self.title, self.max_no_characters)


class Response(CreateModifactionDateMixin, CreatedModificationUserMixin, PublishDataMixin):
    survey = models.ForeignKey(Survey, related_name="responses")
    user = models.ForeignKey('users.User')

    def __str__(self):
        return ("response %s" % self.survey)


class AnswerBase(CreateModifactionDateMixin, CreatedModificationUserMixin, PublishDataMixin):
    question = models.ForeignKey(Question, related_name='answers')
    response = models.ForeignKey(Response, related_name='answers')

    class Meta:
        ordering = ["question__order"]


class AnswerParagraph(AnswerBase):
    body = models.TextField(blank=True, null=True)


class AnswerNumeric(AnswerBase):
    body = models.IntegerField(blank=True, null=True)


class AnswerCheckbox(AnswerBase):
    body = models.TextField(blank=True, null=True)


class AnswerMultipleChoice(AnswerBase):
    body = models.TextField(blank=True, null=True)


class AnswerText(AnswerBase):
    body = models.TextField(blank=True, null=True)

surveys/forms.py
from django import forms

from .models import Survey, SurveyQuestion

class SurveyForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
	    super(SurveyForm, self).__init__(*args, **kwargs)
	    self.fields['q1'].label = SurveyQuestion.objects.first().l_q1

	class Meta:
		model = Survey
		fields = ('q1',)
		widgets = {
			'q1': forms.RadioSelect(attrs={'class':'form-control'})
		}

surveys/views.py
from .models import Survey
from .models import Question
from .models import Response
from .models import AnswerMultipleChoice
from .models import AnswerCheckbox
from .models import AnswerParagraph
from .models import AnswerNumeric
from .models import AnswerText

import json

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

@require_http_methods(['POST'])
@login_required
def agreed_external_survey(request):
    request.user.external_survey_agree = True
    request.user.save()
    return(JsonResponse({ 'external_survey_agree' : request.user.external_survey_agree}, status=200))

@require_http_methods(['GET'])
@login_required
def apply_external_survey(request):
    return(JsonResponse({ 'external_survey_agree' : request.user.external_survey_agree}, status=200))

@require_http_methods(['GET'])
@login_required
def apply_survey(request):
    return(JsonResponse({ 'apply_survey' : ( (Survey.objects.filter(publish=True).count() > 0) and request.user.apply_survey and not request.user.survey_completed())}, status=200))


@login_required
def display_survey(request):
    try:
        survey = Survey.objects.get(publish=True)
    except Exception as e:
        context_dict={ 'Message: ': "Sorry there are no surveys active right now!" }
        return render(request, 'dynamic_survey.html', context_dict)

    questions = survey.questions.all()

    context_dict = {
        'page_title': 'Survey',
        'survey': survey,
        'questions': questions
    }

    return render(request, 'dynamic_survey.html', context_dict)


@require_http_methods(['POST'])
@login_required
def ajax_save_survey(request):
    survey = get_object_or_404(Survey, id = request.POST.get('survey_id'))
    data = json.loads(request.POST.get('survey_data'))
    new_resp = Response(survey=survey, user=request.user)
    new_resp.save()
    for question in data:
        question_id = question.get('id')
        this_question = get_object_or_404(Question, id=question_id)
        if this_question.type == 'multiplechoice':
            choice_value = []
            for question_reponse in question.get('responses'):
               # choice_id = question_reponse.get('id')
                if question_reponse.get('selected'):
                    choice_value.append(question_reponse.get('value'))
            new_answer_multiplechoice = AnswerMultipleChoice(question=this_question, response=new_resp, body="#@#".join(choice_value))
            new_answer_multiplechoice.save()

        if this_question.type == 'checkbox':
            choice_value = []
            for question_reponse in question.get('responses'):
                choice_id = question_reponse.get('id')
                choice_selected = question_reponse.get('selected')
                if choice_selected:
                    choice_value.append(question_reponse.get('value'))
            new_answer_checkbox = AnswerCheckbox(question=this_question, response=new_resp, body="#@#".join(choice_value))
            new_answer_checkbox.save()

        if this_question.type == 'paragraph':
            data_value = question.get('responses')[0].get('value')
            new_answer_paragraph = AnswerParagraph(question=this_question, response=new_resp, body=data_value)
            new_answer_paragraph.save()

        if this_question.type == 'numeric':
            data_value = question.get('responses')[0].get('value')
            new_answer_numeric = AnswerNumeric(question=this_question, response=new_resp, body=int(data_value))
            new_answer_numeric.save()

        if this_question.type == 'text':
            data_value = question.get('responses')[0].get('value')
            new_answer_text = AnswerText(question=this_question, response=new_resp, body=data_value)
            new_answer_text.save()

    return JsonResponse({}, status=200)

surveys/templates/dynamic_survey.html
{% extends 'base.html' %}
{% load static %}

{% block head_css %}
{% endblock %}

{% block page_title %}{{page_title}}{% endblock %}

{% block content %}
<div class="container" id="content">
    <!-- The main page content -->
<div class="row">
	<div class = "col-md-12">
		<div class="panel panel-default">
			<div class="my-panel-heading bg-blue">
				<div class="row">
					<div class="col-xs-11">
						{% if Message %}
							<h1>{{Message}}</h1>
						{% else %}
						<div>
							<h2 style="color:#FFFFFF;">{{survey.title}}</h2>
						</div>
						<h4 style="color:#FFFFFF;">{{survey.description}}</h4>
						{% endif %}
					</div>
					<div class="col-xs-1 text-right m-t-20">
						<i class="fa fa-pencil-square-o"></i>
					</div>
				</div>
			</div>
			<form method="POST" id="survey_form" action="#">
			<div class="panel-body panel-form">
				<div class = "row">
					<div class="col-md-12">
							<!-- List of questions -->
							{% for question in questions %}
								<div class="row m-t-20 m-b-20 m-l-10">
									<div class="col-md-12">
										<div id="question_{{question.id}}" class="question {% if question.is_required %}required{% endif %}" question-type="{{question.type}}">
											<h3>
												{{ forloop.counter }}. {{question.title}} <br/> 
												{% if question.important_text %}
													<small>
														<strong>
															<i class="fa fa-info-circle"></i> {{question.important_text}}
														</strong>
													</small> <br/> 
												{% endif %}
												{% if question.help_text %}
													<small><em>{{question.help_text}}</em></small>
												{% endif %}
											</h3>
											<small class="question_error" style='display:none;'></small>
											{% if question.type == 'multiplechoice' %}
												<div class="row">
													<div class="col-md-8 m-t-10 choices">
														{% for choice in question.multiplechoicequestion.choices.all %}
															
															{% if choice.free_text %}
																<p style="font-size: 1.3em">
																	<input type="radio" class="free_text" name="question_{{question.id}}" id="question_choice_{{choice.id}}" value="{{choice.label}}" style="display:inline-block;" />
																	<input type="text" class="form-control"  placeholder="{{choice.label}}" style="display:inline-block; width:90%;">
																</p>
															{%else%}
																<p style="font-size: 1.3em">
																	<label><input type="radio" name="question_{{question.id}}" id="question_choice_{{choice.id}}" value="{{choice.label}}" /> {{choice.label}}</label>
																</p>
															{% endif %}
														{% endfor %}
													</div>
												</div>
											{% elif question.type == 'checkbox' %}
												<div class="row">
													<div class="col-md-8 m-t-10 choices" min="{{question.checkboxquestion.min_checked}}" max="{{question.checkboxquestion.max_checked}}">
														{% for choice in question.checkboxquestion.choices.all %}
															{% if choice.free_text %}
																<p style="font-size: 1.3em">
																	<input type="checkbox" class="free_text" name="question_{{question.id}}" id="question_choice_{{choice.id}}" value="{{choice.label}}" style="display:inline-block;" />
																	<input type="text" class="form-control"  placeholder="{{choice.label}}" style="display:inline-block; width:90%;">
																</p>
															{%else%}
																<p style="font-size: 1.3em"><label><input type="checkbox" name="question_{{question.id}}" id="question_choice_{{choice.id}}" value="{{choice.label}}" /> {{choice.label}}</label></p>
															{% endif %}
														{% endfor %}
													</div>
												</div>
											{% elif question.type == 'numeric' %}
												<div class="row">
													<div class="col-md-8 m-t-10">
													 	<input type="number" name="quantity" id="question_number_{{choice}}" min="{{question.numericquestion.min_value}}" max="{{question.numericquestion.max_value}}">
													</div>
												</div>
											{% elif question.type == 'paragraph' %}
												<div class="row">
													<div class="col-md-8 m-t-10" question="question_number">
														<textarea rows="4" cols="50" maxlength="{{question.paragraphquestion.max_no_characters}}"></textarea>
													</div>
												</div>
											{%else%}
												<div class="row">
													<div class="col-md-8 m-t-10" maxlength="{{question.textquestion.max_no_characters}}" question="question_text">
														<input type="text">
													</div>
												</div>
											{% endif %}
										</div>
									</div>
								</div>
								{% if not forloop.last %}
									<div class="row">
										<div class="col-md-12">
											<hr/>
										</div>
									</div>
								{% endif %}
							{% endfor %}
						</div>
				</div>
			</div>
			<div class="panel-footer m-t-25">
				<div class="row">
					<div class="col-md-12 text-right m-t-20 m-b-20">
						<button class="btn btn-info btn-block btn-lg bg-blue" type="button" onclick="processSurvey(this)" data-loading-text="Wait a moment..." value="submit">Submit</button>
					</div>
				</div>
				
			</div>
			</form>
		</div>
	</div>
</div>

<div id="survey-completed-modal" class="modal fade">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title">Survey completed!</h3>
			</div>
			<div class="modal-body">
				<p style="font-size: 1.3em">
					Your data was saved succesfully. Thank you for your time, now you'll be redirected to the form.
				</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary btn-lg" data-dismiss="modal">Continue</button>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block tail_js %}
	<script src="{% static 'js/survey_data.js' %}"></script>
	<script type="text/javascript">
		$('#survey-completed-modal').on('hidden.bs.modal', function (e) {
			window.location = "{% url 'data_entry:form' %}";
		});

		function processSurvey(btn)
		{
			$(btn).button('loading');
			var questions = $('.question.required');
			var data_result = validate_survey(questions);
			if(!$('.question_error').is(':visible'))
			{
				$.ajax({
					url : "{% url 'surveys:save_survey' %}",
					type: "POST",
					data : {
						survey_data : JSON.stringify(data_result),
						survey_id : {{survey.id}}
					},
					dataType:'json',
					error: function(jqXHR, textStatus, errorThrown){
						console.log("ERROR");
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
						alert('An error has occured, please contact the systema administrator.');
						$(btn).button('reset');
					},
					success: function(resp) {
						$(btn).button('reset');
						console.log('guardado completado');
						var options = {
							keyboard: false,
							backdrop: 'static'
						};
						$('#survey-completed-modal').modal(options);
						$('#survey-completed-modal').modal('show');

					}
				});
			}
			else
			{
				$(btn).button('reset');
				$('html, body').animate({
        			scrollTop: $('.question_error:visible').first().offset().top - 120
    			}, 700);
			}
		}
	</script>
{% endblock %}