PHRI/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic.base import RedirectView


from users.views import landing, terms, about

urlpatterns = i18n_patterns(
    url(r'^$', landing, name='landing'),
    url(r'^', include('data_entry.urls', namespace='data_entry')),
    url(r'^database/', include('database.urls', namespace='database')),
    url(r'^survey/', include('surveys.urls', namespace='surveys')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^users/password/', include('password_reset.urls')),
    url(r'^favicon.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^terms', terms, name='terms'),
    url(r'^about', about, name='about')
)


### FOR TESTING ONLY ###
from django.http import Http404
from django.core.exceptions import PermissionDenied

def error_403(request):
    raise PermissionDenied

def error_404(request):
    raise Http404

def error_500(request):
    raise Exception('Error!!')

urlpatterns += [
    url(r'^403$', error_403),
    url(r'^404$', error_404),
    url(r'^500$', error_500),
]

data_entry/urls.py
from django.conf.urls import url, include

from . import views


patients = [
   url(r'^$', views.patient_index, name='index'),
   url(r'^test$', views.patient_index_test, name='index_test'),
   url(r'^(?P<patient_id>\d+)/$', views.patient_details, name='details'),
   url(r'^(?P<patient_key>.+)/reports/medical/$', views.medical_report, name='medical_report'),
   url(r'^(?P<patient_key>.+)/reports/medical/email$', views.email_medical_report, name='email_medical_report'),
   url(r'^(?P<patient_key>.+)/reports/patient/$', views.patient_report, name='patient_report'),
   url(r'^(?P<patient_key>.+)/reports/patient/email$', views.email_patient_report, name='email_patient_report'),
]
# reverse('data_entry:patients:index')
# reverse('data_entry:patients:detail')


urlpatterns = [
    url(r'^form$', views.form, name='form'),
    url(r'^form/test$', views.form_test, name='form_test'),
    url(r'^guidelines$', views.guidelines, name='guidelines'),
    url(r'^recommendations$', views.recommendations, name='recommendations'),
    url(r'^patients/', include(patients, namespace='patients')),
]

data_entry/models.py
import json
import io
import csv
import uuid
from datetime import date, datetime

from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

from django_pandas.managers import DataFrameManager

from . import risks
from .choices import *


class Patient(models.Model):
    # random key
    key = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    # Personal Information
    identification = models.CharField(max_length=50)
    first_name = models.CharField(max_length=1, blank=True)
    middle_name = models.CharField(max_length=1, blank=True)
    last_name = models.CharField(max_length=1, blank=True)
    age = models.IntegerField(default=0, validators=[MinValueValidator(18)])
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    #weight in kg
    weight = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    '''
    High-risk angiographic features (PCI Risk):
        1. Multi-vessel PCI
        2. Multiple stents implanted (> 3 stents implanted, > 3 lesions stented)
        3. Complex bifurcation lesion (treated with 2 stents)
        4. Total stent length > 60 mm
        5. Chronic total Occlusion intervention
        6. Bioabsorbable Vascular Scaffold (BVS) implantation
        7. Left main or proximal LAD stenting
    '''
    pci_risk_1 = models.BooleanField(default=False)
    pci_risk_2 = models.BooleanField(default=False)
    pci_risk_3 = models.BooleanField(default=False)
    pci_risk_4 = models.BooleanField(default=False)
    pci_risk_5 = models.BooleanField(default=False)
    pci_risk_6 = models.BooleanField(default=False)
    pci_risk_7 = models.BooleanField(default=False)

    # Procedure Details
    elective_pci = models.CharField(max_length=15, choices=ELECTIVE_PCI_CHOICES)
    bms_stent = models.BooleanField(default=False)
    des_stent = models.BooleanField(default=False)
    bvs = models.BooleanField(default=False)
    poba = models.BooleanField(default=False)
    deb = models.BooleanField(default=False)
    drug_coated_stent = models.BooleanField(default=False)

    # Atrial Fibrillation
    af_type = models.IntegerField(choices=AF_TYPE_CHOICES, blank=True, null=True)
    prev_anti_coagulation = models.IntegerField(default=0, choices=ANTI_COAGULATION_CHOICES, blank=True, null=True)
    warfarin_intolerance = models.BooleanField(default=False)
    inr_instability = models.BooleanField(default=False)
    doac_allergy_or_intolerance = models.BooleanField(default=False)

    #Medical History
    prior_acute_cs = models.BooleanField(default=False)
    prior_stent_thrombosis = models.BooleanField(default=False)
    frailty = models.BooleanField(default=False)
    chf = models.BooleanField(default=False) # CHADS2
    htn = models.IntegerField(default=0, choices=HTN_CHOICES) # CHADS2
    diabetes_mellitus = models.IntegerField(default=0, choices=DIABETES_MELLITUS_CHOICES)

    smoking_history = models.IntegerField(default=0, choices=SMOKING_HISTORY_CHOICES)
    
    tia_stroke_or_sysemb = models.BooleanField(default=False)
    aim = models.BooleanField(default=False)

    vascular_disease = models.IntegerField(default=0, choices=VASCULAR_DISEASE_CHOICES)
    renal_dysfunction = models.BooleanField(default=False)
    liver_dysfunction = models.BooleanField(default=False)
    hx_of_bleeding = models.IntegerField(default=0, choices=BLEEDING_CHOICES)
    alcohol_abuse = models.IntegerField(default=0, choices=ALCOHOL_ABUSE_CHOICES)
    drug_abuse = models.BooleanField(default=False)
    asa_allergy = models.BooleanField(default=False)
    '''
        Creatinine
        A = mg/dL
        B = umol/L
    '''
    creatinine_mgdL = models.FloatField(null=True, blank=True)
    creatinine_umolL = models.FloatField(null=True, blank=True)

    hxoa_anemia = models.BooleanField(default=False)
    hemoglobin_anemia = models.BooleanField(default=False)

    gfr_mLmin = models.FloatField(null=True, blank=True)

    # Recommendation
    ccs_therapy = models.TextField(blank=True)
    agree_therapy = models.BooleanField(default=True)
    reason = models.TextField()
    
    # Meta Info
    user = models.ForeignKey('users.User', related_name='patients')
    created = models.DateTimeField(auto_now_add=True)

    objects= DataFrameManager()

    class Meta:
        ordering = ('-created',)

    def initials(self):
        parts1 = [self.first_name, self.middle_name, self.last_name]
        parts2 = [p for p in parts1 if len(p.strip()) > 0]
        if len(parts2) > 0:
            return '.'.join(parts2)
        else:
            return 'anonymous'

    @property
    def anemia(self):
        return self.hxoa_anemia or self.hemoglobin_anemia

    def stents_display(self):
        display_lst = list()

        if self.bms_stent:
            display_lst.append('BMS')

        if self.des_stent:
            display_lst.append('DES')
        
        if self.bvs:
            display_lst.append('BVS')

        if self.drug_coated_stent:
            display_lst.append('DRUG COATED STENT')
        
        if self.poba:
            display_lst.append('POBA')

        if self.deb:
            display_lst.append('DEB')

        if len(display_lst) > 0:
            return ", ".join(display_lst)
        else:
            return 'None'

    def chads2_score(self):
        # boolean values are converted to ints (1s or 0s)
        chf_value = int(self.chf)
        # htn is an integer field with 3 possible choices (0, 1 and 2)
        # for chads2, 1 or 2 get converted to True, and then to 1
        # 0 gets converted to False, and then to 0
        htn_value = int(bool(self.htn))
        age_value = int(self.age >= 75)
        diabetes_value = int(self.diabetes_mellitus)
        tia_stroke_or_sysemb_value = 2*(int(self.tia_stroke_or_sysemb))
        return chf_value + htn_value + age_value + diabetes_value + tia_stroke_or_sysemb_value

    def chads2_score_interpretation(self):
        if self.chads2_score() <= 2:
            return 'LOW'
        else:
            return 'HIGH'

    def chads2_risk(self):
        return risks.chads2[self.chads2_score()]

    def cha2_score(self):
        chf_value = int(self.chf)
        # htn is an integer field with 3 possible choices (0, 1 and 2)
        # 1 or 2 gets converted to 1; 0 gets converted to False, and then to 0
        htn_value = int(bool(self.htn))
        age_in_6574_value = int(self.age >= 65) # Age 65-74, logically: Age>=65
        age_greater_than_75_value = int(self.age >= 75)
        diabetes_value = int(self.diabetes_mellitus)
        tia_stroke_or_sysemb_value = 2 * (int(self.tia_stroke_or_sysemb))
        vascular_disease_value = int(self.vascular_disease != 0)
        female_value = int(self.gender == 'F')
        return chf_value + htn_value + age_in_6574_value + age_greater_than_75_value + \
               diabetes_value + tia_stroke_or_sysemb_value + vascular_disease_value + female_value

    def cha2_risk(self):
        return risks.cha2[self.cha2_score()]

    def hasbled_score(self):
        '''
            HASBLED = HTN* (only Yes, uncontrolled on meds SBP>160 mmHg) + Renal Dysfunction + Liver Dysfuntion + Stroke + History of bleeding + Labile INR + Age>=65 + 1*(Alcohol >= 8 drinks/week OR Drugs)
        '''
        # htn is an integer field with 3 possible choices (0, 1 and 2)
        # for hasbled, choice 2 should have a value of 1
        # choices 0 and 1 should have a value of 0
        htn_value = int(bool(self.htn == 2))
        renal_dysfunction_value = int(self.renal_dysfunction)
        liver_dysfunction_value = int(self.liver_dysfunction)
        tia_stroke_or_sysemb_value = int(self.tia_stroke_or_sysemb)
        aim_value = int(self.aim)
        bleeding_value = int(self.hx_of_bleeding != 0)
        inr_value = int(self.inr_instability)
        age_value = int(self.age >= 65)
        drugs_value = int(self.drug_abuse)
        alcohol_abuse_value = int(bool(self.alcohol_abuse == 2))
        return htn_value + renal_dysfunction_value + liver_dysfunction_value + tia_stroke_or_sysemb_value + \
               bleeding_value + inr_value + age_value + (drugs_value or alcohol_abuse_value) + aim_value
               #bleeding_value + inr_value + age_value + drugs_value + alcohol_abuse_value + aim_value

    def hasbled_score_interpretation(self):
        if self.hasbled_score() <= 3:
            return 'LOW'
        else:
            return 'HIGH'

    def hasbled_risk(self):
        return risks.hasbled[self.hasbled_score()]

    def parse_ccs_therapy(self):
        return json.loads(self.ccs_therapy)


    def field_csv(self, value, type):
        empty = not bool(value)

        if type is str:
            return value or 'N/A'
        elif type is int:
            return str(value) if not empty else 'N/A'
        elif type is float:
            return '{0:.2f}'.format(value) if not empty else 'N/A'
        elif type is bool:
            return 'Yes' if value else 'No'
        elif type is date:
            return value.strftime('%m/%d/%Y') if not empty else 'N/A'
        elif type is datetime:
            return value.strftime('%m/%d/%Y %H:%M:%S') if not empty else 'N/A'

    def csv(self):
        buf = io.StringIO()
        writer = csv.writer(buf)
        writer.writerow([
            self.field_csv(self.identification, str),
            self.field_csv(self.initials(), str),
            self.field_csv(self.age, int),
            self.field_csv(self.get_gender_display(), str),
            self.field_csv(self.weight, float),
            self.field_csv(self.pci_risk_1, bool),
            self.field_csv(self.pci_risk_2, bool),
            self.field_csv(self.pci_risk_3, bool),
            self.field_csv(self.pci_risk_4, bool),
            self.field_csv(self.pci_risk_5, bool),
            self.field_csv(self.pci_risk_6, bool),
            self.field_csv(self.pci_risk_7, bool),
            self.field_csv(self.elective_pci, str),

data_entry/forms.py
from django import forms
from django.conf import settings

from .models import Patient


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ('user',)


class EmailForm(forms.Form):
    address = forms.EmailField()

data_entry/templates/data_entry/patients/index.html
{% extends 'base.html' %}
{% load static %}

{% block head_css %}
    <link href="{% static 'plugins/DataTables/media/css/dataTables.bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'plugins/DataTables/extensions/Select/css/select.bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css' %}" rel="stylesheet" />
{% endblock %}

{% block page_title %}My Patients{% endblock %}

{% block menu2 %}active{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="my-panel-heading bg-blue">
            <div class="row">
                <div class="col-xs-12">Patients</div>
            </div>
        </div>
        <div class="panel-body f-s-14">
            <table id="data-table" class="table table-striped table-condensed table-bordered table-hover">
                <thead>
                    <tr>
                        <th data-orderable="false">I.D.</th>
                        <th>Initials</th>
                        <th>Gender</th>
                        <th>Age</th>
                        <th>Creation Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for patient in patients %}
                        <tr>
                            <td>{{ patient.identification }}</td>
                            <td>{{ patient.initials }}</td>
                            <td>{{ patient.get_gender_display }}</td>
                            <td>{{ patient.age }}</td>
                            <td>{{ patient.created|date:"Y/m/d" }}</td>
                            <td>
                                <a type="button" class="btn btn-sm btn-success" href="{% url 'data_entry:patients:medical_report' patient.key %}" target="_blank"><i class="fa fa-user-md"></i> Medical Report</a>
                                <a type="button" class="btn btn-sm btn-warning" href="{% url 'data_entry:patients:patient_report' patient.key %}" target="_blank"><i class="fa fa-user"></i> Patient Report</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block tail_js %}
    <script src="{% static 'plugins/DataTables/media/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'plugins/DataTables/media/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Select/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
    <script>
        var handleDataTableSelect = function() {
            "use strict";
            
            if ($('#data-table').length !== 0) {
                $('#data-table').DataTable({
                    responsive: true,
                    order: [[ 4, "desc" ]],
                    // columnDefs: [
                    //     {targets: 0, orderable: false},
                    //     {targets: 2, orderable: false},
                    //     {targets: 5, orderable: false},
                    // ]
                    // processing: true,
                    // serverSide: true,
                    // ajax: '/patients/',
                    // select: {
                    //     style: 'single'
                    // }
                });
            }
        };

        var TableManageTableSelect = function () {
            "use strict";
            return {
                //main function
                init: function () {
                    handleDataTableSelect();
                }
            };
        }();

        TableManageTableSelect.init();
    </script>
{% endblock %}

data_entry/templates/data_entry/patients/print.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Patient</title>
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <style>
        hr {
            margin-top:2px;
            margin-bottom: 2px;
        }

        table th{
            white-space: nowrap;
        }

        table td, th{
            padding:0px !important;
            border-top: none !important;
        }

        @media print{
            body {
                padding: 5px 10px!important;
            }

            blockquote {
                border: none;
            }
        }
    </style>
</head>
<body style="padding:20px 300px;">
    <h2 class="text-center" style="font-weight:500;">TRIPLE THERAPY REPORT: Patient Data</h2>

    <h3>Personal Information</h3>
    <hr />
    <table class="table" style="width:100%;border:none;">
        <thead
            <tr>
                <td style="width:32%"></td>
                <td style="width:12%"></td>
                <td style="width:12%"></td>
                <td style="width:32%"></td>
                <td style="width:12%"></td>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>Identification Number</th>
                <td>{{ patient.identification }}</td>
                <td></td>
                <th>Name</th>
                <td>{{ patient.full_name }}</td>
            </tr>

            <tr>
                <th>Gender</th>
                <td>{{ patient.get_gender_display }}</td>
                <td></td>
                <th>Date Of Birth</th>
                <td>{{ patient.date_of_birth|date:"d/m/Y" }}</td>
            </tr>

            <tr>
                <th>Age</th>
                <td>{{ patient.age }}</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>

    <h3>Procedure Details</h3>
    <hr/>
    <table class="table" style="width:100%;border:none;">
        <thead>
            <tr>
                <td style="width:32%"></td>
                <td style="width:12%"></td>
                <td style="width:12%"></td>
                <td style="width:32%"></td>
                <td style="width:12%"></td>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>Date</th>
                <td>{{ patient.date_of_procedure|date:"d/m/Y" }}</td>
                <td></td>
                <th>Indication</th>
                <td>{{ patient.indication }}</td>
            </tr>

            <tr>
                <th>Vessels PCI</th>
                <td>{{ patient.vessels_pci_display }}</td>
                <td></td>
                <th>Stent</th>
                <td>{{ patient.get_stent_display }}</td>
            </tr>

            <tr>
                <th>Balloons</th>
                <td>{{ patient.balloons }}</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>

    <h3>Atrial Fibrilation</h3>
    <hr/>
    <table class="table" style="width:100%;border:none;">
        <thead>
            <tr>
                <td style="width:32%"></td>
                <td style="width:12%"></td>
                <td style="width:12%"></td>
                <td style="width:32%"></td>
                <td style="width:12%"></td>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>Indication</th>
                <td>{{ patient.get_indication_display }}</td>
                <td></td>
                <th>Previous Anti-Coagulation</th>
                <td>{{ patient.get_prev_anti_coagulation_display }}</td>
            </tr>

            <tr>
                <th>Warfarin Intolerance</th>
                <td>{{ patient.warfarin_intolerance|yesno|capfirst }}</td>
                <td></td>
                <th>INR Instability</th>
                <td>{{ patient.inr_instability|yesno|capfirst }}</td>
            </tr>

            <tr>
                <th>NOAC Allergy Or Intollerance</th>
                <td>{{ patient.noac_allergy_or_intolerance|yesno|capfirst }}</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>

    <h3>Blood Work</h3>
    <hr/>
    <table class="table" style="width:100%;border:none;">
        <thead>
            <tr>
                <td style="width:11%"></td>
                <td style="width:15%"></td>
                
                <td style="width:11%"></td>
                
                <td style="width:11%"></td>
                <td style="width:15%"></td>
                
                <td style="width:11%"></td>

                <td style="width:11%"></td>
                <td style="width:15%"></td>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>HB</th>
                <td>{{ patient.hb|default:"N/A" }} {{ patient.get_hb_um_display }}</td>

                <td></td>

                <th>PLTS</th>
                <td>{{ patient.plts|default:"N/A" }} {{ patient.get_plts_um_display }}</td>

                <td></td>

                <th>CREAT</th>
                <td>{{ patient.creat|default:"N/A" }} {{ patient.get_creat_um_display }}</td>
            </tr>

            <tr>
                <th>AST</th>
                <td>{{ patient.ast|default:"N/A" }} {{ patient.get_ast_um_display }}</td>

                <td></td>
                
                <th>ALT</th>
                <td>{{ patient.alt|default:"N/A" }} {{ patient.get_alt_um_display }}</td>
                
                <td></td>

                <th>GGT</th>
                <td>{{ patient.ggt|default:"N/A" }} {{ patient.get_ggt_um_display }}</td>
            </tr>

            <tr>
                <th>Bilirubin</th>
                <td>{{ patient.bilirubin|default:"N/A" }} {{ patient.get_bilirubin_um_display }}</td>

                <td></td>
                
                <th>Troponin</th>
                <td>{{ patient.troponin|default:"N/A" }} {{ patient.get_troponin_um_display }}</td>
                
                <td></td>

                <th>INR</th>
                <td>{{ patient.inr|default:"N/A" }}</td>
            </tr>

            <tr>
                <th>EGFR</th>
                <td colspan="7">{{ patient.egfr|default:"N/A" }} {{ patient.get_egfr_um_display }}</td>
            </tr>
        </tbody>
    </table>

    <h3>Medical History</h3>
    <hr/>
    <table class="table" style="width:100%;border:none;">
        <thead>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>HTN</th>
                <td>{{ patient.get_htn_display }}</td>
                
                <td></td>

                <th>Vascular Disease</th>
                <td>{{ patient.get_vascular_disease_display }}</td>
            </tr>

            <tr>
                <th>Hx Of Bleeding</th>
                <td>{{ patient.get_hx_of_bleeding_display }}</td>
                
                <td></td>

                <th>Alcohol Abuse</th>
                <td>{{ patient.get_alcohol_abuse_display }}</td>
            </tr>

            <tr>
                <th>Hx Of Malignancy</th>
                <td>{{ patient.get_hx_of_malignancy_display }}</td>
                
                <td></td>

                <th>Upcoming Non-Cardiatic Surgery</th>
                <td>{{ patient.get_upcoming_non_cardiatic_surgery_display }}</td>
            </tr>

            <tr>
                <th>CHF</th>
                <td>{{ patient.chf|yesno|capfirst }}</td>
                
                <td></td>

                <th>Diabetes Mellitus</th>
                <td>{{ patient.diabetes_mellitus|yesno|capfirst }}</td>

            </tr>

            <tr>
                <th>Stroke</th>
                <td>{{ patient.stroke|yesno|capfirst }}</td>
                
                <td></td>

                <th>TIA</th>
                <td>{{ patient.tia|yesno|capfirst }}</td>
            </tr>

            <tr>
                <th>Renal Dysfunction</th>
                <td>{{ patient.renal_dysfunction|yesno|capfirst }}</td>
                
                <td></td>

                <th>Drug Abuse</th>
                <td>{{ patient.drug_abuse|yesno|capfirst }}</td>
            </tr>

            <tr>
                <th>Chronic NSAIDS RX</th>
                <td>{{ patient.chronic_nsaids_rx|yesno|capfirst }}</td>
                
                <td></td>

                <th>Excessive Fall Risk</th>
                <td>{{ patient.excessive_fall_risk|yesno|capfirst }}</td>
            </tr>

            <tr>
                <th>ASA Allergy</th>
                <td>{{ patient.asa_allergy|yesno|capfirst }}</td>
            </tr>
        </tbody>
    </table>

    <center style="font-weight:bolder">www.tripletherapy.net</center>
    <!-- *************************** PAGE BREAK ****************************** -->
    <div style="page-break-after: always;"></div>

    <h2 class="text-center" style="font-weight:500;">TRIPLE THERAPY REPORT: Results</h2>

    <h3>Scores and Risks</h3>
    <hr />

    <h4>CHADS<sub>2</sub></h4>
    <table class="table" style="width:100%;border:none;">
        <thead>
            <tr>
                <td style="width:20%;">
                <td style="width:80%;">
            </td>
        </tr>
        <tbody>
            <tr>
                <th>Score</th>
                <td class="text-left">{{ patient.chads2_score }}</td>
            </tr>

            <tr>
                <th>Associated Risk:</th>
                <td class="text-left">{{ patient.chads2_risk.percentage }}% <small> ({{ patient.chads2_risk.ci }}) 95% C.I.</small></td>
            </tr>
        </tbody>
    </table>

    <br/>

    <h4>CHA<sub>2</sub>DS<sub>2</sub>-VASc</h4>
    <table class="table" style="width:100%;border:none;">
        <thead>
            <tr>
                <td style="width:20%;">
                <td style="width:80%;">
            </td>
        </tr>
        <tbody>
            <tr>
                <th>Score</th>
                <td class="text-left">{{ patient.cha2_score }}</td>
            </tr>

            <tr>
                <th>Associated Risk:</th>
                <td class="text-left">{{ patient.cha2_risk.percentage }}%</td>
            </tr>
        </tbody>
    </table>

    <br/>

    <h4>HAS-BLED</h4>
    <table class="table" style="width:100%;border:none;">
        <thead>
            <tr>
                <td style="width:20%;">
                <td style="width:80%;">
            </td>
        </tr>
        <tbody>
            <tr>
                <th>Score</th>
                <td class="text-left">{{ patient.hasbled_score }}</td>
            </tr>

            <tr>
                <th>Associated Risk:</th>
                <td class="text-left">{{ patient.hasbled_risk.percentage }}%</td>
            </tr>
        </tbody>
    </table>

    <br/>

    <h3>Recommended Therapy</h3>
    <hr />
    <p style="font-size:18px;">{{ patient.recommended_therapy }}<p>

    {% if patient.followed_recommendation %}
        <p style="font-size:14px;">The therapy recommendation is being followed.<p>
    {% else %}
        <p style="font-size:14px;">The therapy recommendation is <strong>not</strong> being followed.<p>

        <blockquote>
            <p><i>"{{ patient.reason_not_followed }}"</i></p>
            <footer>{{ patient.user.guess_user_name }} ({{ user.email }})</footer>
        </blockquote>
    {% endif %}


    <p class="f-w-700">Report generated on {% now "d/m/Y" %} by {{ user.guess_user_name }} ({{ user.email }})</p>

    <center style="font-weight:bolder">www.tripletherapy.net</center>
</body>
</html>

data_entry/templates/data_entry/patients/table.html
        <!-- begin col-6 -->
        <!-- <div class="col-md-6">
            <!-- begin panel -->
            <div class="panel panel-inverse" data-sortable-id="table-basic-1">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">Default Table</h4>
                </div>
                <div class="panel-body">
                    <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Full Name</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-6 -->