PHRI/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic.base import RedirectView


from users.views import landing, terms, about

urlpatterns = i18n_patterns(
    url(r'^$', landing, name='landing'),
    url(r'^', include('data_entry.urls', namespace='data_entry')),
    url(r'^database/', include('database.urls', namespace='database')),
    url(r'^survey/', include('surveys.urls', namespace='surveys')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^users/password/', include('password_reset.urls')),
    url(r'^favicon.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^terms', terms, name='terms'),
    url(r'^about', about, name='about')
)


### FOR TESTING ONLY ###
from django.http import Http404
from django.core.exceptions import PermissionDenied

def error_403(request):
    raise PermissionDenied

def error_404(request):
    raise Http404

def error_500(request):
    raise Exception('Error!!')

urlpatterns += [
    url(r'^403$', error_403),
    url(r'^404$', error_404),
    url(r'^500$', error_500),
]

data_entry/urls.py
from django.conf.urls import url, include

from . import views


patients = [
   url(r'^$', views.patient_index, name='index'),
   url(r'^test$', views.patient_index_test, name='index_test'),
   url(r'^(?P<patient_id>\d+)/$', views.patient_details, name='details'),
   url(r'^(?P<patient_key>.+)/reports/medical/$', views.medical_report, name='medical_report'),
   url(r'^(?P<patient_key>.+)/reports/medical/email$', views.email_medical_report, name='email_medical_report'),
   url(r'^(?P<patient_key>.+)/reports/patient/$', views.patient_report, name='patient_report'),
   url(r'^(?P<patient_key>.+)/reports/patient/email$', views.email_patient_report, name='email_patient_report'),
]
# reverse('data_entry:patients:index')
# reverse('data_entry:patients:detail')


urlpatterns = [
    url(r'^form$', views.form, name='form'),
    url(r'^form/test$', views.form_test, name='form_test'),
    url(r'^guidelines$', views.guidelines, name='guidelines'),
    url(r'^recommendations$', views.recommendations, name='recommendations'),
    url(r'^patients/', include(patients, namespace='patients')),
]

database/urls.py
from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dump$', views.dump, name='dump'),
    url(r'^survey/(?P<survey_id>\d+)/dump$', views.get_survey_csv, name='get_survey_csv'),
    url(r'^filter$', views.filter, name='filter'),
]

surveys/urls.py
from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^$', views.display_survey, name='dynamic_survey'),
    url(r'^save/$', views.ajax_save_survey, name='save_survey'),
    url(r'^iapply/$', views.apply_survey, name='iapply'),
    url(r'^extiapply/$', views.apply_external_survey, name='extiapply'),
    url(r'^external_survey/agreed$', views.agreed_external_survey, name='extsurveyagreed'),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^(?P<user_id>\d+)$', views.profile, name='profile'),
    url(r'^exists$', views.exists, name='exists'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^me$', views.me, name='me'),
    url(r'^register$', views.register, name='register'),
    url(r'^verification_sent$', views.verification_sent, name='verification_sent'),
    url(r'^verify/(?P<code>.+)$', views.verify, name='verify'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block head_css %}
{% endblock %}

{% block page_title %}About{% endblock %}

{% block menu6 %}active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="my-panel-heading bg-blue">
                    <div class="row">
                        <div class="col-xs-12">
                            About
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>What is this?</h3>
                            <p class="lead text-justify">
                                The <b>ORACLE</b> <em>(On-Line Physician Decision Support Tool for the Management of Oral Anticoagulation in Patients with Atrial Fibrillation Undergoing Percutaneous Coronary Intervention)</em> Project is an alliance of several academic physicians motivated by the gap in knowledge and unmet needs in the management of patients with Atrial Fibrillation that undergo PCI. The team is composed by General Cardiologists, Interventional Cardiologists, Arrhythmia and Hematology Specialists, and knowledge translation experts. The purpose of this group is to provide and facilitate the use of a decision tool for the management of oral anticoagulation in patients with atrial fibrillation undergoing PCI with the ultimate goals of improving the appropriate use of guidelines and improving outcomes and net clinical benefit.
                            </p>
                            <p class="lead text-justify">
                                Concerned with the lack of evidence and conflicting recommendations regarding the role of dual antiplatelet and triple therapy management in patients with atrial fibrillation undergoing PCI the ORACLE investigators have conducted preliminary surveys that indicate that the majority (80%) of physicians surveyed use the CCS guidelines, however only 33% correctly selected the appropriate recommendations demonstrating a significant gap in knowledge. To overcome the multiple possible combinations of DAPT and triple therapy in this population, a web-based decision tool has been developed with the goal of facilitating physician’s decision making, refining guideline adherence and eventually improving safety and efficacy outcomes in this challenging population.
                            </p>
                            {% comment %}
                            <!--p class="lead text-justify">
                                The <b>Triple Therapy Aid</b> tool helps physicians make informed decisions. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur porta libero vel purus accumsan, in efficitur libero efficitur. Ut lobortis quam quis bibendum fermentum. Donec sodales mauris dui, non porta magna vestibulum sed. Morbi pretium augue quis cursus aliquam. Aliquam sodales tortor luctus massa vestibulum rhoncus.
                            </p>

                            <h3>Who is it for?</h3>
                            <p class="lead text-justify">
                                Quisque non risus gravida, porta mi sed, malesuada diam. Phasellus mauris metus, semper iaculis pharetra et, feugiat non augue. Sed augue orci, semper et eros at, sollicitudin tincidunt quam. Quisque viverra, mi at sollicitudin eleifend, magna mauris gravida ex, a lobortis arcu libero et nisl.
                            </p>

                            <h3>Research group</h3>
                            <p class="lead text-justify">
                                Ut a dapibus mauris. Nulla ac dolor eu ligula dignissim consectetur. Donec faucibus dignissim efficitur. Quisque non porttitor nisi. Aliquam eget arcu vitae dolor mattis congue mattis non velit.
                            </p>

                            <h3>Sponsors</h3>
                            <ul class="lead text-justify">
                                <li><b>Sed eget tempus nisi.</b> Nunc bibendum quam vel tellus dictum, ut iaculis tellus facilisis. Duis auctor quam nec tempor sagittis. Etiam mollis eu dolor a lobortis. </li>
                                <li><b>Etiam ultricies nulla sed augue rhoncus auctor.</b> Nullam commodo urna at mauris facilisis, ut placerat nunc aliquet. Nam scelerisque elementum eros vitae mattis. </li>
                                <li><b>Mauris et ante tellus.</b> Curabitur vel elementum dolor. Praesent lectus ex, tincidunt nec pulvinar ac, iaculis ut urna.</li>
                            </ul-->
                            {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-2">
            <img alt="Madhu Natarajan" class="img-thumbnail img-responsive" src="{% static 'img/team/01-mn-team.png' %}"/>
            <ul class="list-group">
                <li class="list-group-item">
                    <h4>Madhu Natarajan</h4>
                </li>
            </ul>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <img alt="Sumeet Gandhi" class="img-thumbnail img-responsive" src="{% static 'img/team/02-sg-team.png' %}"/>
            <ul class="list-group">
                <li class="list-group-item">
                    <h4>Sumeet Gandhi</h4>
                </li>
            </ul>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <img alt="Natalia Pinilla-Echeverri" class="img-thumbnail img-responsive" src="{% static 'img/team/03-npe-team.png' %}"/>
            <ul class="list-group">
                <li class="list-group-item">
                    <h4>Natalia Pinilla-Echeverri</h4>
                </li>
            </ul>
        </div>

        <div class="col-sm-6 col-md-4 col-lg-2">
            <img alt="Carlos Morillo" class="img-thumbnail img-responsive" src="{% static 'img/team/04-cm-team.png' %}"/>
            <ul class="list-group">
                <li class="list-group-item">
                    <h4>Carlos Morillo</h4>
                </li>
            </ul>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <img alt="MSam Schulman" class="img-thumbnail img-responsive" src="{% static 'img/team/05-ss-team.png' %}"/>
            <ul class="list-group">
                <li class="list-group-item">
                    <h4>Sam Schulman</h4>
                </li>
            </ul>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <img alt="JD Schwalm" class="img-thumbnail img-responsive" src="{% static 'img/team/06-jds-team.png' %}"/>
            <ul class="list-group">
                <li class="list-group-item">
                    <h4>JD Schwalm</h4>
                </li>
            </ul>
        </div>
    </div>

{% endblock %}

templates/base.html
{% extends 'base_theme.html' %}
{% load static %}
{% load i18n %}

{% block body %}
    <!-- begin #page-loader -->
    <div id="page-loader" class="fade in"><span class="spinner"></span></div>
    <!-- end #page-loader -->

    <!-- begin #page-container -->
    <div id="page-container" class="fade page-without-sidebar page-header-fixed in">

        <div id="header" class="header navbar navbar-default navbar-fixed-top">
            <!-- begin container-fluid -->
            <div class="container-fluid f-s-14" style="padding-left:0px">
                <!-- begin mobile sidebar expand / collapse button -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- end mobile sidebar expand / collapse button -->

                <!-- begin navbar-collapse -->
                <div class="collapse navbar-collapse pull-left" style="width:100%;" id="top-navbar">
                    <ul class="nav navbar-nav" style="width:100%">
                        <li class="{% block menu1 %}{% endblock %}">
                            <a href="{% url 'data_entry:form' %}">
                                <i class="fa fa-pencil-square-o"></i>
                                <span>{% trans 'Patient Form' %}</span>
                            </a>
                        </li>
                        <li class="{% block menu2 %}{% endblock %}">
                            <a href="{% url 'data_entry:patients:index' %}">
                                <i class="fa fa-users"></i>
                                <span>{% trans 'My Patients' %}</span>
                            </a>
                        </li>
                        {% if user.researcher %}
                        <li class="{% block menu3 %}{% endblock %}">
                            <a href="{% url 'database:index' %}">
                                <i class="fa fa-database"></i>
                                <span>{% trans 'Database' %}</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="{% block menu4 %}{% endblock %}">
                            <a href="{% url 'data_entry:guidelines' %}">
                                <i class="fa fa-book"></i>
                                <span>{% trans 'Guidelines' %}</span>
                            </a>
                        </li>
                        <li class="{% block menu5 %}{% endblock %}">
                            <a href="{% url 'data_entry:recommendations' %}">
                                <i class="fa fa-book"></i>
                                <span>{% trans 'Recommendations' %}</span>
                            </a>
                        </li>
                        <li class="{% block menu6 %}{% endblock %}">
                            <a href="{% url 'about' %}">
                                <i class="fa fa-info-circle"></i>
                                <span>{% trans 'About' %}</span>
                            </a>
                        </li>
                        <li class="dropdown navbar-user pull-right">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span class="">{{ user.user_name|default:"Anonymous" }}</span> <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu animated fadeInLeft f-s-14">
                                <li><a href="{% url 'users:me' %}">{% trans 'Edit Profile' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'users:logout' %}">{% trans 'Log Out' %}</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>

                <!-- <div class="collapse navbar-collapse pull-right">
                    <ul class="nav navbar-nav navbar-right f-s-14">
                        <li class="dropdown navbar-user">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span class="">{{ user.user_name|default:"Anonymouse" }}</span> <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu animated fadeInLeft f-s-14">
                                <li><a href="{% url 'users:me' %}">{% trans 'Edit Profile' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'users:logout' %}">{% trans 'Log Out' %}</a></li>
                            </ul>
                        </li>
                    </ul>
                </div> -->
                <!-- end navbar-collapse -->
                <!-- Aqui iba el menu de usuario -->
                <!-- begin header navigation right -->

                <!-- end header navigation right -->
            </div>
            <!-- end container-fluid -->
        </div>


        <!-- begin #logos -->
        <div id="logos" class="logos row bg-white vertical-align">
            <div class="col-xs-12 col-sm-4 text-center">
                <img src="{% static 'img/logos/logo_phri.png' %}"/>
            </div>

            <div class="col-xs-12 col-sm-4 text-center">
                <img src="{% static 'img/logos/logo_hhs.jpg' %}"/>
            </div>

            <div class="col-xs-12 col-sm-4 text-center">
                <img src="{% static 'img/logos/logo_mmu.jpg' %}"/>
            </div>
        </div>

        <!-- begin #content -->
        <div id="content" class="content">
            {% block content %}
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-inverse">
                        <div class="panel-heading">
                            <div class="panel-heading-btn">
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                            </div>
                            <h4 class="panel-title">Panel Title here</h4>
                        </div>
                        <div class="panel-body">
                            Panel Content Here
                        </div>
                    </div>
                </div>
            </div>
            {% endblock %}
        </div>
        <!-- end #content -->

        <!-- begin scroll to top btn -->
        <a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
        <!-- end scroll to top btn -->
    </div>
    <!-- end page container -->
{% endblock %}

templates/base_theme.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <title>{% block page_title %}{% endblock %}</title>
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />

        <!-- ================== BEGIN BASE CSS STYLE ================== -->
        <link href="{% static 'css/open_sans.css' %}" rel="stylesheet">
        <link href="{% static 'plugins/jquery-ui/themes/base/minified/jquery-ui.min.css' %}" rel="stylesheet" />
        <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
        <link href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" />
        <link href="{% static 'plugins/gritter/css/jquery.gritter.css' %}" rel="stylesheet" />
        <link href="{% static 'css/animate.min.css' %}" rel="stylesheet" />

        {# TODO: Minify style.css and change this href to style.min.css #}
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />

        <link href="{% static 'css/style-responsive.min.css' %}" rel="stylesheet" />
        <link href="{% static 'css/theme/blue.css' %}" rel="stylesheet" id="theme" />
        <!-- ================== END BASE CSS STYLE ================== -->

        <!-- ================== BEGIN BASE JS ================== -->
        <script src="{% static 'plugins/pace/pace.min.js' %}"></script>
        <!-- ================== END BASE JS ================== -->

        {% block head_css %}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% block body %}
        <h1>Base Theme</h1>
        {% endblock %}

        <div id="messages" style="display:none;">
        {% if messages %}
            {% for message in messages %}
            <div>
                <h1>{{ message.tags|upper }}</h1>
                <p>{{ message }}</p>
            </div>
            {% endfor %}
        {% endif %}
        </div>

        <div id="survey-confirmation-agreement" class="modal fade">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h3 class="modal-title">Survey Agreement</h3>
              </div>
              <div class="modal-body">
                <p style="font-size: 1.3em">
                    Before accessing the application, we would appreciate if you agree to complete a Survey that will collect information on your current practice and management of patients with atrial fibrillation and coronary artery disease. We also want you to be aware that the information collected after using the application will be used for operational and monitoring purposes.
                </p>

                <p style="font-size: 1.3em">
                    No personal identifiers such as your name, your e-mail address or affiliations will be disclosed to any other third parties.
                </p>

                <p style="font-size: 1.3em">
                    Do you agree to complete the Survey and consent to use the information collected in the Survey and Application for research purposes?
                </p>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-primary btn-lg">I Agree</button>
                  <button type="button" class="btn btn-link text-danger">I Don't Agree</button>
              </div>
            </div>
          </div>
        </div>

        <div id="external-survey-confirmation-agreement" class="modal fade">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Survey Agreement</h3>
                </div>
                <div class="modal-body">
                    <p style="font-size: 1.3em">
                        Before accessing the application, we would appreciate if you agree to complete a Survey that will collect information on your current practice and management of patients with atrial fibrillation and coronary artery disease. We also want you to be aware that the information collected after using the application will be used for operational and monitoring purposes.
                    </p>
    
                    <p style="font-size: 1.3em">
                        No personal identifiers such as your name, your e-mail address or affiliations will be disclosed to any other third parties.
                    </p>
    
                    <p style="font-size: 1.3em">
                        Do you agree to complete the Survey and consent to use the information collected in the Survey and Application for research purposes?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary btn-lg">I Agree</button>
                    <button type="button" class="btn btn-link text-danger">I Don't Agree</button>
                </div>
                </div>
            </div>
            </div>

        <!-- ================== BEGIN BASE JS ================== -->
        <script src="{% static 'plugins/jquery/jquery-1.9.1.min.js' %}"></script>
        <script src="{% static 'plugins/jquery/jquery-migrate-1.1.0.min.js' %}"></script>
        <script src="{% static 'plugins/jquery-ui/ui/minified/jquery-ui.min.js' %}"></script>
        <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
        <!--[if lt IE 9]>
            <script src="{% static 'crossbrowserjs/html5shiv.js' %}"></script>
            <script src="{% static 'crossbrowserjs/respond.min.js' %}"></script>
            <script src="{% static 'crossbrowserjs/excanvas.min.js' %}"></script>
        <![endif]-->
        <script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
        <script src="{% static 'plugins/jquery-cookie/jquery.cookie.js' %}"></script>
        <script src="{% static 'plugins/gritter/js/jquery.gritter.min.js' %}"></script>
        <script src="{% static 'plugins/markdown-js/js/markdown.min.js' %}"></script>
        <!-- ================== END BASE JS ================== -->

        <!-- ================== BEGIN PAGE LEVEL JS ================== -->
        <script src="{% static 'js/apps.js' %}"></script>
        <!-- ================== END PAGE LEVEL JS ================== -->

        <script>
            var static_url = "{% static '' %}";
            $(document).ready(function() {
                App.init();
            });
        </script>

        <script src="https://cdn.ravenjs.com/3.10.0/raven.min.js" crossorigin="anonymous"></script>
        <script>
            Raven.config('https://d221725a2815476dba351ab7d36d50bf@sentry.io/138345').install();
        </script>
        {% block tail_js %}
        {% endblock %}

        <script>
            $('#messages').children().each(function(index, element){
                $.gritter.add({
                    title: $(element).children('h1').html(),
                    text: $(element).children('p').html(),
                    time: 50000,
                    position: 'bottom-left'
                });
            });
        </script>
        <script type="text/javascript">
            /*$.get("{% url 'surveys:iapply'  %}", function( data ) {
                if( data.apply_survey ) {
                    switch( window.location.pathname.toString() ) {
                        case '{% url "surveys:dynamic_survey" %}':
                            break;
                        default:
                            var options = {
                                keyboard: false,
                                backdrop: 'static'
                            };
                            $('#survey-confirmation-agreement').modal(options);
                            $('#survey-confirmation-agreement').modal('show');
                            break;
                    }
                }
            });*/

            /*$('#survey-confirmation-agreement button.btn-primary').on('click', function(){
                window.location = "{% url 'surveys:dynamic_survey'%}";
            });

            $('#survey-confirmation-agreement button.btn-link').on('click', function(){
                window.location = "{% url 'users:logout' %}";
            });*/
            $.get("{% url 'surveys:extiapply'  %}", function( data ) {
                var currentUrl = window.location.pathname.toString();
                var excludeUrls = [
                    "{% url 'users:exists' %}",
                    "{% url 'users:login' %}",
                    "{% url 'users:logout' %}",
                    "{% url 'users:me' %}",
                    "{% url 'users:register' %}",
                    "{% url 'users:verification_sent' %}",
                    "{% url 'password_reset_recover' %}",
                ];
                if( !data.external_survey_agree && excludeUrls.indexOf(currentUrl) == -1) {
                    var options = {
                        keyboard: false,
                        backdrop: 'static'
                    };
                    $('#external-survey-confirmation-agreement').modal(options);
                    $('#external-survey-confirmation-agreement').modal('show');
                }
            });
            
            $('#external-survey-confirmation-agreement button.btn-primary').on('click', function(){
                $.ajaxSetup({
                    beforeSend: function(xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    }
                });
                $.post("{% url 'surveys:extsurveyagreed'  %}", function( data ) {
                    window.open("https://redc.phri.ca/redcap/surveys/?s=KFJL3JF87X", "_blank");
                    window.location.reload();
                });
            });

            
            $('#external-survey-confirmation-agreement button.btn-link').on('click', function(){
                window.location = "{% url 'users:logout' %}";
            });
        </script>
    </body>
</html>