PHRI/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic.base import RedirectView


from users.views import landing, terms, about

urlpatterns = i18n_patterns(
    url(r'^$', landing, name='landing'),
    url(r'^', include('data_entry.urls', namespace='data_entry')),
    url(r'^database/', include('database.urls', namespace='database')),
    url(r'^survey/', include('surveys.urls', namespace='surveys')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^users/password/', include('password_reset.urls')),
    url(r'^favicon.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^terms', terms, name='terms'),
    url(r'^about', about, name='about')
)


### FOR TESTING ONLY ###
from django.http import Http404
from django.core.exceptions import PermissionDenied

def error_403(request):
    raise PermissionDenied

def error_404(request):
    raise Http404

def error_500(request):
    raise Exception('Error!!')

urlpatterns += [
    url(r'^403$', error_403),
    url(r'^404$', error_404),
    url(r'^500$', error_500),
]

database/urls.py
from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dump$', views.dump, name='dump'),
    url(r'^survey/(?P<survey_id>\d+)/dump$', views.get_survey_csv, name='get_survey_csv'),
    url(r'^filter$', views.filter, name='filter'),
]

database/models.py
from django.db import models

# Create your models here.

database/views.py
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse
from django.http import StreamingHttpResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied

from data_entry.utils import patients_csv, patients_csv_size_estimate, survey_csv # returns a generator

from data_entry.models import Patient 
from surveys.models import Survey


@login_required
def index(request):
    if not request.user.researcher:
        raise PermissionDenied

    surveys = Survey.objects.all()
    context = {
        'csv_size_estimate': patients_csv_size_estimate(), 
        'surveys' : surveys
    }
    return render(request, 'database/index.html', context)


@login_required
def get_survey_csv(request, survey_id):
    if not request.user.researcher:
        raise PermissionDenied
    filename = 'survey_{0}_{1}.txt'.format(survey_id, timezone.now().strftime('%Y%m%d'))
    resp = StreamingHttpResponse(survey_csv(survey_id), content_type='text/plain; charset=utf-8')
    resp['Content-Disposition'] = 'attachment; filename="{0}"'.format(filename)
    return resp

@login_required
def dump(request):
    if not request.user.researcher:
        raise PermissionDenied
    filename = 'patient_dump_{0}.csv'.format(timezone.now().strftime('%Y%m%d'))
    resp = StreamingHttpResponse(patients_csv(), content_type='text/csv; charset=utf-8')
    resp['Content-Disposition'] = 'attachment; filename="{0}"'.format(filename)
    return resp


@login_required
def filter(request):
    df = Patient.objects.all().to_dataframe()
    ...
    ...
    return HttpResponse(df.to_html())

database/templates/database/index.html
{% extends 'base.html' %}
{% load static %}

{% block head_css %}
{% endblock %}

{% block page_title %}Database{% endblock %}

{% block menu3 %}active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="my-panel-heading bg-blue">
                    <div class="row">
                        <div class="col-xs-12">
                            Patients' Data
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="{% url 'database:dump' %}" class="btn btn-primary btn-block" style="font-size:70px"><i class="fa fa-table" aria-hidden="true"></i></a>
                        </div>

                        <div class="col-md-8">
                            <p class="lead">Download all patient records in one file (CSV format)</p>
                            <p class="muted">This file includes patient data from every registered user. Estimated filesize: <strong>{{ csv_size_estimate|filesizeformat  }}</strong></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% for s in surveys %}
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="my-panel-heading bg-blue">
                    <div class="row">
                        <div class="col-xs-12">
                            {{ s.title }}
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="{% url 'database:get_survey_csv' s.id %}" class="btn btn-primary btn-block" style="font-size:70px"><i class="fa fa-table" aria-hidden="true"></i></a>
                        </div>

                        <div class="col-md-8">
                            <p class="lead">Download all - {{ s.title }} - records in one file (CSV format)</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}